name: Keep Render Bot Awake

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:       # Allows manual trigger

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render app to keep awake
        run: |
          curl -fsSL https://algographbot.onrender.com/ || echo "Failed to ping Render"
